# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jalapp', '0003_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'Python'), ('dj', 'Django'), ('st', 'Software Testing'), ('sql', 'SQL'), ('UI', 'UI')], max_length=15)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('Morning', 'Morning Shifts'), ('Afternoon', 'Afternoon Shifts'), ('Evening', 'Evening Shifts'), ('Night', 'Night Shifts')], max_length=31)),
                ('start_date', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
